/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/register": {
    /** @description Register a new user */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            username: string;
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description User created */
        201: {
          content: never;
        };
        /** @description Invalid input or user already exists */
        400: {
          content: never;
        };
      };
    };
  };
  "/auth/login": {
    /** @description Login user */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Logged in */
        200: {
          content: never;
        };
        /** @description Invalid credentials */
        401: {
          content: never;
        };
      };
    };
  };
  "/auth/me": {
    /** @description Get current user session */
    get: {
      responses: {
        /** @description Current user info */
        200: {
          content: {
            "application/json": {
              id: number;
              username: string;
              email: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
      };
    };
  };
  "/auth/logout": {
    /** @description Logout current user */
    post: {
      responses: {
        /** @description Logged out successfully */
        200: {
          content: never;
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
      };
    };
  };
  "/resources": {
    /** @description List resources */
    get: {
      parameters: {
        query?: {
          type?: "seed" | "compost" | "harvest" | "labor";
          search?: string;
          ownerId?: string;
          minQuantity?: string;
        };
      };
      responses: {
        /** @description List of resources */
        200: {
          content: {
            "application/json": ({
                id: number;
                title: string;
                description?: string;
                /** @enum {string} */
                type: "seed" | "compost" | "harvest" | "labor";
                quantity: number;
                unit: string;
                ownerId: number;
                ownerUsername: string | null;
                status: string;
                latitude?: number;
                longitude?: number;
                createdAt: string;
              })[];
          };
        };
      };
    };
    /** @description Create a new resource */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            title: string;
            description?: string;
            /** @enum {string} */
            type: "seed" | "compost" | "harvest" | "labor";
            quantity: number;
            unit: string;
            latitude?: number;
            longitude?: number;
          };
        };
      };
      responses: {
        /** @description Resource created */
        201: {
          content: never;
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
      };
    };
  };
  "/resources/{id}": {
    /** @description Delete a resource */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Resource deleted */
        200: {
          content: never;
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Resource not found */
        404: {
          content: never;
        };
      };
    };
    /** @description Update a resource */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            title?: string;
            description?: string;
            /** @enum {string} */
            type?: "seed" | "compost" | "harvest" | "labor";
            quantity?: number;
            unit?: string;
            latitude?: number;
            longitude?: number;
          };
        };
      };
      responses: {
        /** @description Resource updated */
        200: {
          content: never;
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Resource not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/trades": {
    /** @description List user trades */
    get: {
      responses: {
        /** @description List of trades */
        200: {
          content: {
            "application/json": ({
                id: number;
                initiatorId: number;
                receiverId: number;
                initiatorUsername: string | null;
                receiverUsername: string | null;
                resources: {
                    title: string;
                    quantity: number;
                    unit: string;
                  }[];
                status: string;
                createdAt?: unknown;
              })[];
          };
        };
      };
    };
    /** @description Propose a new trade */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            receiverId: number;
            resourceIds: number[];
          };
        };
      };
      responses: {
        /** @description Trade created */
        201: {
          content: never;
        };
        /** @description Invalid resources */
        400: {
          content: never;
        };
      };
    };
  };
  "/trades/{id}": {
    /** @description Get trade details */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Trade details */
        200: {
          content: {
            "application/json": {
              id: number;
              initiatorId: number;
              receiverId: number;
              status: string;
              createdAt?: unknown;
              initiatorUsername: string | null;
              receiverUsername: string | null;
              resources: {
                  title: string;
                  quantity: number;
                  unit: string;
                  ownerId: number;
                  type: string;
                }[];
            };
          };
        };
        /** @description Trade not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/trades/{id}/accept": {
    /** @description Accept a trade */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Trade accepted */
        200: {
          content: never;
        };
        /** @description Conflict - Resources unavailable */
        409: {
          content: never;
        };
      };
    };
  };
  "/trades/{id}/cancel": {
    /** @description Cancel a pending trade */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Trade cancelled */
        200: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
      };
    };
  };
  "/trades/{id}/reject": {
    /** @description Reject a pending trade */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Trade rejected */
        200: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
      };
    };
  };
  "/notifications": {
    /** @description List user notifications */
    get: {
      responses: {
        /** @description List of notifications */
        200: {
          content: {
            "application/json": ({
                id: number;
                userId: number;
                type: string;
                content: string;
                isRead: boolean;
                tradeId: number | null;
                resourceId: number | null;
                createdAt: string;
              })[];
          };
        };
      };
    };
  };
  "/notifications/{id}/read": {
    /** @description Mark a notification as read */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Notification updated */
        200: {
          content: never;
        };
      };
    };
  };
  "/notifications/read-all": {
    /** @description Mark all notifications as read */
    post: {
      responses: {
        /** @description All notifications updated */
        200: {
          content: never;
        };
      };
    };
  };
  "/users/me": {
    /** @description Get current user profile */
    get: {
      responses: {
        /** @description User profile */
        200: {
          content: {
            "application/json": {
              id: number;
              username: string;
              bio: string | null;
              themeColor: string | null;
              createdAt?: unknown;
            };
          };
        };
      };
    };
    /** @description Update current user profile */
    patch: {
      requestBody?: {
        content: {
          "application/json": {
            bio?: string;
            themeColor?: string;
          };
        };
      };
      responses: {
        /** @description Profile updated */
        200: {
          content: {
            "application/json": {
              id: number;
              username: string;
              bio: string | null;
              themeColor: string | null;
            };
          };
        };
      };
    };
  };
  "/users/search": {
    /** @description Search for users */
    get: {
      parameters: {
        query?: {
          search?: string;
        };
      };
      responses: {
        /** @description User list */
        200: {
          content: {
            "application/json": ({
                id: number;
                username: string;
                bio: string | null;
                themeColor: string | null;
              })[];
          };
        };
      };
    };
  };
  "/users/{id}": {
    /** @description Get user profile by ID */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description User profile */
        200: {
          content: {
            "application/json": {
              id: number;
              username: string;
              bio: string | null;
              themeColor: string | null;
              createdAt?: unknown;
            };
          };
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/social-api/request": {
    /** @description Send a friend request */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            friendId: number;
          };
        };
      };
      responses: {
        /** @description Friend request sent */
        201: {
          content: never;
        };
        /** @description Invalid request */
        400: {
          content: never;
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/social-api/accept": {
    /** @description Accept a friend request */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            requesterId: number;
          };
        };
      };
      responses: {
        /** @description Friend request accepted */
        200: {
          content: never;
        };
        /** @description Request not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/social-api/reject": {
    /** @description Reject a friend request */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            requesterId: number;
          };
        };
      };
      responses: {
        /** @description Friend request rejected */
        200: {
          content: never;
        };
        /** @description Request not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/social-api/friends": {
    /** @description List current user friends */
    get: {
      responses: {
        /** @description List of friends */
        200: {
          content: {
            "application/json": ({
                id: number;
                username: string;
                bio: string | null;
                themeColor: string | null;
              })[];
          };
        };
      };
    };
  };
  "/social-api/requests": {
    /** @description List pending friend requests */
    get: {
      responses: {
        /** @description List of pending requests */
        200: {
          content: {
            "application/json": ({
                id: number;
                username: string;
                bio: string | null;
                themeColor: string | null;
                requestId: number;
                createdAt?: unknown;
              })[];
          };
        };
      };
    };
  };
  "/social-api/outbound-requests": {
    /** @description List outbound friend requests */
    get: {
      responses: {
        /** @description List of outbound requests */
        200: {
          content: {
            "application/json": ({
                id: number;
                username: string;
                bio: string | null;
                themeColor: string | null;
                requestId: number;
                createdAt?: unknown;
              })[];
          };
        };
      };
    };
  };
  "/social-api/friends/{id}": {
    /** @description Remove a friend */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Friend removed */
        200: {
          content: never;
        };
        /** @description Friendship not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/social-api/friends/{id}/interactions": {
    /** @description Get unified interactions with a friend */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Timeline of messages and trades */
        200: {
          content: {
            "application/json": ({
                id: number;
                /** @enum {string} */
                interactionType: "MESSAGE" | "TRADE";
                senderId?: number | null;
                receiverId: number;
                initiatorId?: number | null;
                content?: string | null;
                status?: string | null;
                isRead?: boolean | null;
                createdAt?: unknown;
              })[];
          };
        };
      };
    };
  };
  "/messages/{friendId}": {
    /** Get messages with a friend */
    get: {
      parameters: {
        path: {
          friendId: string;
        };
      };
      responses: {
        /** @description List of messages */
        200: {
          content: {
            "application/json": ({
                id: number;
                senderId: number;
                receiverId: number;
                content: string;
                isRead: boolean | null;
                createdAt?: unknown;
              })[];
          };
        };
      };
    };
  };
  "/messages": {
    /** Send a message */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            receiverId: number;
            content: string;
          };
        };
      };
      responses: {
        /** @description Message sent */
        201: {
          content: {
            "application/json": {
              id: number;
              senderId: number;
              receiverId: number;
              content: string;
              isRead: boolean | null;
              createdAt?: unknown;
            };
          };
        };
      };
    };
  };
  "/messages/read/{friendId}": {
    /** Mark messages as read */
    post: {
      parameters: {
        path: {
          friendId: string;
        };
      };
      responses: {
        /** @description Messages marked as read */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: {
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
